version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE